language: node_js
node_js:
  - 13

services:
  - docker

script:
  # - docker image prune --all
  - docker-compose-f docker-compose-build.yaml
  - docker tag udagram-frontend huyphamjj/udagram-frontend
  - docker tag udagram-api-user huyphamjj/udagram-api-user
  - docker tag udagram-api-feed huyphamjj/udagram-api-feed
  - docker tag reverseproxy huyphamjj/reverseproxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push huyphamjj/udagram-frontend
  - docker push huyphamjj/udagram-api-user
  - docker push huyphamjj/udagram-api-feed
  - docker push huyphamjj/reverseproxy

