language: node_js
node_js:
  - 13

services:
  - docker

script:
  # - docker image prune --all
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-frontend:2.0 huyphamjj/udagram-frontend:2.0
  - docker tag udagram-api-user:2.0 huyphamjj/udagram-api-user:2.0
  - docker tag udagram-api-feed:2.0 huyphamjj/udagram-api-feed:2.0
  - docker tag reverseproxy:2.0 huyphamjj/reverseproxy:2.0

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push huyphamjj/udagram-frontend:local:2.0
  - docker push huyphamjj/udagram-api-user:2.0
  - docker push huyphamjj/udagram-api-feed:2.0
  - docker push huyphamjj/reverseproxy:2.0

