apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-deployment
  namespace: default
  labels:
    app: backend-user
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: huyphamjj/udagram-api-user:latest
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - sleep 15
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: POSTGRES_HOST
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AWS_PROFILE
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AWS_BUCKET
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: JWT_SECRET
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        ports:
          - containerPort: 8080
