apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-service
  namespace: default
  labels:
    app: reverseproxy
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: reverseproxy
