apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-deployment
  namespace: default
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: huyphamjj/reverseproxy:2.0
        ports:
        - containerPort: 8080
        